### ISSUE TITLE
Interested, but where the SQL schema?

### ISSUE THREAD

**Issue by aluemku** [edvin/tooldb#1]

**Comment by edvin** [comment]
I've dumped the schema with some sample data into /db.sql now. After I created this I've learned quite a bit more about how tools should be structured. I'll eventually create a complete open source tool management system with a lot more details and interaction with everything from machine tools to presetters as well as api/imports from tool manufacturers.

**Comment by aluemku** [comment]
That sounds great. Thank you for the schema. This project already helps a lot ...
